#%RAML 0.8
title: eZ Platform Content Repository
version: v2

baseUri: http://{host}/api/ezp/v2
protocols: [HTTP, HTTPS]
mediaType: application/xml

schemas:
    - BinaryInput: !include schemas/xsd/BinaryInput.xsd
    - CommonDefinitions: !include schemas/xsd/CommonDefinitions.xsd
    - ContentCreate: !include schemas/xsd/ContentCreate.xsd
    - ContentObjectState: !include schemas/xsd/ContentObjectState.xsd
    - ContentTypeCreate: !include schemas/xsd/ContentTypeCreate.xsd
    - ContentTypeGroup: !include schemas/xsd/ContentTypeGroup.xsd
    - ContentTypeUpdate: !include schemas/xsd/ContentTypeUpdate.xsd
    - ContentType: !include schemas/xsd/ContentType.xsd
    - ContentUpdate: !include schemas/xsd/ContentUpdate.xsd
    - Content: !include schemas/xsd/Content.xsd
    - ErrorMessage: !include schemas/xsd/ErrorMessage.xsd
    - FieldDefinitionCreate: !include schemas/xsd/FieldDefinitionCreate.xsd
    - FieldDefinitionUpdate: !include schemas/xsd/FieldDefinitionUpdate.xsd
    - FieldDefinition: !include schemas/xsd/FieldDefinition.xsd
    - FieldValue: !include schemas/xsd/FieldValue.xsd
    - Limitation: !include schemas/xsd/Limitation.xsd
    - LocationCreate: !include schemas/xsd/LocationCreate.xsd
    - LocationUpdate: !include schemas/xsd/LocationUpdate.xsd
    - Location: !include schemas/xsd/Location.xsd
    - ObjectRelation: !include schemas/xsd/ObjectRelation.xsd
    - ObjectStateGroup: !include schemas/xsd/ObjectStateGroup.xsd
    - ObjectState: !include schemas/xsd/ObjectState.xsd
    - Policy: !include schemas/xsd/Policy.xsd
    - Relation: !include schemas/xsd/Relation.xsd
    - Role: !include schemas/xsd/Role.xsd
    - Root: !include schemas/xsd/Root.xsd
    - Section: !include schemas/xsd/Section.xsd
    - SessionInput: !include schemas/xsd/SessionInput.xsd
    - Session: !include schemas/xsd/Session.xsd
    - StringTypes: !include schemas/xsd/StringTypes.xsd
    - Trash: !include schemas/xsd/Trash.xsd
    - UrlAlias: !include schemas/xsd/UrlAlias.xsd
    - UrlWildcard: !include schemas/xsd/UrlWildcard.xsd
    - UserCreate: !include schemas/xsd/UserCreate.xsd
    - UserGroupCreate: !include schemas/xsd/UserGroupCreate.xsd
    - UserGroupUpdate: !include schemas/xsd/UserGroupUpdate.xsd
    - UserGroup: !include schemas/xsd/UserGroup.xsd
    - UserUpdate: !include schemas/xsd/UserUpdate.xsd
    - User: !include schemas/xsd/User.xsd
    - VersionInfo: !include schemas/xsd/VersionInfo.xsd
    - VersionList: !include schemas/xsd/VersionList.xsd
    - VersionUpdate: !include schemas/xsd/VersionUpdate.xsd
    - Version: !include schemas/xsd/Version.xsd
    - View: !include schemas/xsd/View.xsd

